### ISSUE TITLE
M4: Missing state

### ISSUE THREAD

**Issue by gniezen** [mrstegeman/hap-controller-node#18]
When I run the `pair-setup.js` example with a BLE device (Eve smart plug), I keep on getting a `M4: Missing State` error. Any ideas on what I'm doing wrong or how to debug this further?

**Comment by mrstegeman** [comment]
Is the device unpaired from every other controller, e.g. all iOS devices? If unsure, you can reset it via the reset button.

**Comment by gniezen** [comment]
I've reset it a couple of times, and checked that it's not listed in my Home app anymore. I'm wondering if it could be related to the Bluetooth stack I'm using, i.e., I'm on Linux.

**Comment by mrstegeman** [comment]
Yes, that’s the other common problem. The `noble` library has caused me all kinds of problems similar to this.

**Comment by mrstegeman** [comment]
This should be fixed in v0.5.0. See #32.
