### ISSUE TITLE
Support randomly generated setup codes

### ISSUE THREAD

**Issue by snorp** [mrstegeman/hap-controller-node#2]
Right now it's not possible to support devices with random setup codes, because we do all phases of pairing immediately. It looks like we need a different flow where we do the M1 first, then only continue after the user gives us the code.

**Comment by mrstegeman** [comment]
Do you have a device you'd recommend testing with? I've only encountered two scenarios:
1. Code is known ahead of time, via sticker.
2. Code is generated in software and given to the Home app in iOS (code is never seen).

In case 2, I have no idea how to proceed.

**Comment by snorp** [comment]
In my case it's an Ecobee 3 thermostat. It displays the code on the screen only after you do the M1 phase.

**Comment by mrstegeman** [comment]
Hmm... I'll have to think through the process here.
