### ISSUE TITLE
Pairing issue

### ISSUE THREAD

**Issue by narf007** [mrstegeman/hap-controller-node#22]
Hello,
	I'm using your library in order to built a controller that I've tested with my own accessory built with an ESP32 and a Homekit library. When I try to pair with my accessory, the accessory returns an issue because the controller seems to start a pairing using MFi certification protocols (pairing METHOD = 1). Is my accessory faulty or am I using your library in the wrong way ? Is there a way (a property to set) to choose the pairing method ? Thank you in advance for your feedback.

**Comment by mrstegeman** [comment]
This was implemented from the community version of the HAP spec. What should be changed to change the pairing method?

**Comment by narf007** [comment]
I was just asking if there is a way to change the pairing method in the library you implemented ?  A function or a parameter to use ?

**Comment by mrstegeman** [comment]
No, there's not, because i didn't know there was a different method.

**Comment by mrstegeman** [comment]
@narf007 What issue/error are you actually seeing from this library?

**Comment by mrstegeman** [comment]
This should be fixed in v0.5.0. See #32.
